services:
    mcfedr_doctrine_delay_queue_driver.worker:
        class: Mcfedr\DoctrineDelayQueueDriverBundle\Worker\DoctrineDelayWorker
        arguments:
            - "@mcfedr_queue_manager.registry"
