services:
    mcfedr_doctrine_delay_queue_driver.worker:
        class: Mcfedr\DoctrineDelayQueueDriverBundle\Worker\DoctrineDelayWorker
        calls:
            - [setContainer, ["@service_container"]]
